# Generated by Django 4.2.6 on 2023-10-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='send_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=1000)),
                ('Email', models.EmailField(max_length=50)),
                ('PhoneNumber', models.ImageField(upload_to='')),
                ('Name', models.TextField()),
            ],
        ),
    ]
