# Generated by Django 4.2.6 on 2023-10-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_dynamic_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_data',
            name='PhoneNumber',
            field=models.IntegerField(max_length=10),
        ),
    ]
