# Generated by Django 4.2.6 on 2023-10-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_send_data_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_data',
            name='PhoneNumber',
            field=models.IntegerField(),
        ),
    ]
