# Generated by Django 4.2.6 on 2023-10-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_send_data_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic_data',
            name='Adress',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamic_data',
            name='admin',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
