# Generated by Django 4.2.6 on 2023-10-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_dynamic_data_adress_dynamic_data_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_data',
            name='PhoneNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
